module.exports = [
	{
		'entity': 'SM',
		'app': 'Adam',
		'entityName': 'Service Manager',
		'type': 'author',
		'roles': [
			{ id: 'PMDSD', name: 'Manage Data Services Design', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PMDSE', name: 'Manage Data Services Experience', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PMDSR', name: 'Manage Data Services Roles', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PVDSD', name: 'View Data Services Design', operations: [{ method: 'GET' }] },
			{ id: 'PVDSE', name: 'View Data Services Experience', operations: [{ method: 'GET' }] },
			{ id: 'PVDSR', name: 'View Data Services Roles', operations: [{ method: 'GET' }] },
			{ id: 'PVDSA', name: 'View Data Services Audit', operations: [{ method: 'GET' }] },
			/*********** */
			{ id: 'PNDSB', name: 'No Access Data Services Basic Details', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PVDSB', name: 'View Data Services Basic Details', operations: [{ method: 'GET' }] },
			{ id: 'PMDSBC', name: 'Create Data Services', operations: [{ method: 'POST' }] },
			{ id: 'PMDSBU', name: 'Update Data Services', operations: [{ method: 'PUT' }] },
			{ id: 'PMDSBD', name: 'Remove Data Services', operations: [{ method: 'DELETE' }] },
			{ id: 'PMDSPD', name: 'Manage Deploy Data Services', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PMDSPS', name: 'Manage Start/Stop Data Services ', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSPD', name: 'No Access Deploy Data Services', operations: [{ method: 'PUT' }] },
			{ id: 'PNDSPS', name: 'No Access Start/Stop Data Services', operations: [{ method: 'PUT' }] },
			{ id: 'PVDSIDPR', name: 'View Data Services PreHook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIDPR', name: 'Manage Data Services PreHook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIDPR', name: 'No Access Data Services PreHook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIDPO', name: 'View Data Services PostHook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIDPO', name: 'Manage Data Services PostHook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIDPO', name: 'No Access Data Services PostHook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIRSU', name: 'View Data Services Submit Hook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIRSU', name: 'Manage Data Services Submit Hook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIRSU', name: 'No Access Data Services Submit Hook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIRAP', name: 'View Data Services Approve Hook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIRAP', name: 'Manage Data Services Approve Hook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIRAP', name: 'No Access Data Services Approve Hook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIRRJ', name: 'View Data Services Reject Hook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIRRJ', name: 'Manage Data Services Reject Hook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIRRJ', name: 'No Access Data Services Reject Hook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIRDI', name: 'View Data Services Discard Hook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIRDI', name: 'Manage Data Services Discard Hook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIRDI', name: 'No Access Data Services Discard Hook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSIRRW', name: 'View Data Services Rework Hook', operations: [{ method: 'GET' }] },
			{ id: 'PMDSIRRW', name: 'Manage Data Services Rework Hook', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSIRRW', name: 'No Access Data Services Rework Hook', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSDH', name: 'View Data Services Data History', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSDH', name: 'Manage Data Services Data History', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSDH', name: 'No Access Data Services Data History', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSPD', name: 'View Data Services Permannent Delete', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSPD', name: 'Manage Data Services Permannent Delete', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSPD', name: 'No Access Data Services Permannent Delete', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSRE', name: 'View Data Services Reset Setting', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSRE', name: 'Manage Data Services Reset Setting', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSRE', name: 'No Access Data Services Reset Setting', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSEP', name: 'View Data Services End-Point Setting', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSEP', name: 'Manage Data Services End-Point Setting', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSEP', name: 'No Access Data Services End-Point Setting', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSFS', name: 'View Data Services Fuzzy Search Setting', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSFS', name: 'Manage Data Services Fuzzy Search Setting', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSFS', name: 'No Access Data Services Fuzzy Search Setting', operations: [{ method: 'PUT' }, { method: 'GET' }] },
			{ id: 'PVDSSPR', name: 'View Data Services Property Setting', operations: [{ method: 'GET' }] },
			{ id: 'PMDSSPR', name: 'Manage Data Services Property Setting', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNDSSPR', name: 'No Access Data Services Property Setting', operations: [{ method: 'PUT' }, { method: 'GET' }] }

		],
		'default': 'R',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'W',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'R',
					'PVDSB': 'R',
					'PMDSBC': 'W',
					'PMDSBU': 'W',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'R',
					'PNDSPS': 'R',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'R',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'R',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'R',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'R',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'R',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'R',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'R',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'R',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'R',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'R',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'R',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'R',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'R'

				}
			},
			'name': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'W',
					'PMDSBU': 'W',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'N',
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'W',
					'PMDSBU': 'W',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'R',
				}
			},
			'collectionName': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'permanentDeleteData': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'W',
					'PNDSSPD': 'N'
				}
			},
			'app': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'W',
					'PMDSE': 'W',
					'PMDSR': 'W',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'W',
					'PMDSBU': 'W',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'W',
					'PNDSIDPR': 'R',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'W',
					'PNDSIDPO': 'R',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'W',
					'PNDSIRSU': 'R',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'W',
					'PNDSIRAP': 'R',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'W',
					'PNDSIRRJ': 'R',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'W',
					'PNDSIRDI': 'R',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'W',
					'PNDSIRRW': 'R',
					'PVDSSDH': 'R',
					'PMDSSDH': 'W',
					'PNDSSDH': 'R',
					'PVDSSRE': 'R',
					'PMDSSRE': 'W',
					'PNDSSRE': 'R',
					'PVDSSEP': 'R',
					'PMDSSEP': 'W',
					'PNDSSEP': 'R',
					'PVDSSFS': 'R',
					'PMDSSFS': 'W',
					'PNDSSFS': 'R',
					'PVDSSPR': 'R',
					'PMDSSPR': 'W',
					'PNDSSPR': 'R',
					'PVDSSPD': 'R',
					'PMDSSPD': 'W',
					'PNDSSPD': 'N',
				}
			},
			'api': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'W',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'port': {
				'_t': 'Number',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'wizard': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'W',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'R',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'version': {
				'_t': 'Number',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'R',
					'PMDSBU': 'R',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'R',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'N',
				}
			},
			'instances': {
				'_t': 'Number',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'versionValidity': {
				'_t': 'Object',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'W',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'definition': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'W',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'attributeList': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'W',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'status': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'R',
					'PMDSBU': 'R',
					'PMDSBD': 'R',
					'PMDSPD': 'W',
					'PMDSPS': 'W',
					'PNDSPD': 'R',
					'PNDSPS': 'R',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'N',
				}
			},
			'internalVersion': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'comment': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'relatedSchemas': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'R',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}

			},
			'webHooks': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'W',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'preHooks': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'W',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'workflowHooks': {
				'postHooks': {
					'submit': {
						'_t': 'Array',
						'_p': {
							'PMDSD': 'N',
							'PMDSE': 'N',
							'PMDSR': 'N',
							'PVDSD': 'N',
							'PVDSE': 'N',
							'PVDSR': 'N',
							'PVDSA': 'N',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'N',
							'PMDSBC': 'N',
							'PMDSBU': 'N',
							'PMDSBD': 'N',
							'PMDSPD': 'N',
							'PMDSPS': 'N',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'N',
							'PMDSIDPR': 'N',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'N',
							'PMDSIDPO': 'N',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'R',
							'PMDSIRSU': 'W',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'N',
							'PMDSIRAP': 'N',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'N',
							'PMDSIRRJ': 'N',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'N',
							'PMDSIRDI': 'N',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'N',
							'PMDSIRRW': 'N',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'N',
							'PMDSSDH': 'N',
							'PNDSSDH': 'N',
							'PVDSSRE': 'N',
							'PMDSSRE': 'N',
							'PNDSSRE': 'N',
							'PVDSSEP': 'N',
							'PMDSSEP': 'N',
							'PNDSSEP': 'N',
							'PVDSSFS': 'N',
							'PMDSSFS': 'N',
							'PNDSSFS': 'N',
							'PVDSSPR': 'N',
							'PMDSSPR': 'N',
							'PNDSSPR': 'N',
							'PVDSSPD': 'N',
							'PMDSSPD': 'N',
							'PNDSSPD': 'N',
						}
					},
					'approve': {
						'_t': 'Array',
						'_p': {
							'PMDSD': 'N',
							'PMDSE': 'N',
							'PMDSR': 'N',
							'PVDSD': 'N',
							'PVDSE': 'N',
							'PVDSR': 'N',
							'PVDSA': 'N',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'N',
							'PMDSBC': 'N',
							'PMDSBU': 'N',
							'PMDSBD': 'N',
							'PMDSPD': 'N',
							'PMDSPS': 'N',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'N',
							'PMDSIDPR': 'N',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'N',
							'PMDSIDPO': 'N',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'N',
							'PMDSIRSU': 'N',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'R',
							'PMDSIRAP': 'W',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'N',
							'PMDSIRRJ': 'N',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'N',
							'PMDSIRDI': 'N',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'N',
							'PMDSIRRW': 'N',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'N',
							'PMDSSDH': 'N',
							'PNDSSDH': 'N',
							'PVDSSRE': 'N',
							'PMDSSRE': 'N',
							'PNDSSRE': 'N',
							'PVDSSEP': 'N',
							'PMDSSEP': 'N',
							'PNDSSEP': 'N',
							'PVDSSFS': 'N',
							'PMDSSFS': 'N',
							'PNDSSFS': 'N',
							'PVDSSPR': 'N',
							'PMDSSPR': 'N',
							'PNDSSPR': 'N',
							'PVDSSPD': 'N',
							'PMDSSPD': 'N',
							'PNDSSPD': 'N',
						}
					},
					'reject': {
						'_t': 'Array',
						'_p': {
							'PMDSD': 'N',
							'PMDSE': 'N',
							'PMDSR': 'N',
							'PVDSD': 'N',
							'PVDSE': 'N',
							'PVDSR': 'N',
							'PVDSA': 'N',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'N',
							'PMDSBC': 'N',
							'PMDSBU': 'N',
							'PMDSBD': 'N',
							'PMDSPD': 'N',
							'PMDSPS': 'N',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'N',
							'PMDSIDPR': 'N',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'N',
							'PMDSIDPO': 'N',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'N',
							'PMDSIRSU': 'N',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'N',
							'PMDSIRAP': 'N',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'R',
							'PMDSIRRJ': 'W',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'N',
							'PMDSIRDI': 'N',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'N',
							'PMDSIRRW': 'N',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'N',
							'PMDSSDH': 'N',
							'PNDSSDH': 'N',
							'PVDSSRE': 'N',
							'PMDSSRE': 'N',
							'PNDSSRE': 'N',
							'PVDSSEP': 'N',
							'PMDSSEP': 'N',
							'PNDSSEP': 'N',
							'PVDSSFS': 'N',
							'PMDSSFS': 'N',
							'PNDSSFS': 'N',
							'PVDSSPR': 'N',
							'PMDSSPR': 'N',
							'PNDSSPR': 'N',
							'PVDSSPD': 'N',
							'PMDSSPD': 'N',
							'PNDSSPD': 'N',
						}
					},
					'discard': {
						'_t': 'Array',
						'_p': {
							'PMDSD': 'N',
							'PMDSE': 'N',
							'PMDSR': 'N',
							'PVDSD': 'N',
							'PVDSE': 'N',
							'PVDSR': 'N',
							'PVDSA': 'N',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'N',
							'PMDSBC': 'N',
							'PMDSBU': 'N',
							'PMDSBD': 'N',
							'PMDSPD': 'N',
							'PMDSPS': 'N',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'N',
							'PMDSIDPR': 'N',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'N',
							'PMDSIDPO': 'N',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'N',
							'PMDSIRSU': 'N',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'N',
							'PMDSIRAP': 'N',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'N',
							'PMDSIRRJ': 'N',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'R',
							'PMDSIRDI': 'W',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'N',
							'PMDSIRRW': 'N',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'N',
							'PMDSSDH': 'N',
							'PNDSSDH': 'N',
							'PVDSSRE': 'N',
							'PMDSSRE': 'N',
							'PNDSSRE': 'N',
							'PVDSSEP': 'N',
							'PMDSSEP': 'N',
							'PNDSSEP': 'N',
							'PVDSSFS': 'N',
							'PMDSSFS': 'N',
							'PNDSSFS': 'N',
							'PVDSSPR': 'N',
							'PMDSSPR': 'N',
							'PNDSSPR': 'N',
						}
					},
					'rework': {
						'_t': 'Array',
						'_p': {
							'PMDSD': 'N',
							'PMDSE': 'N',
							'PMDSR': 'N',
							'PVDSD': 'N',
							'PVDSE': 'N',
							'PVDSR': 'N',
							'PVDSA': 'N',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'N',
							'PMDSBC': 'N',
							'PMDSBU': 'N',
							'PMDSBD': 'N',
							'PMDSPD': 'N',
							'PMDSPS': 'N',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'N',
							'PMDSIDPR': 'N',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'N',
							'PMDSIDPO': 'N',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'N',
							'PMDSIRSU': 'N',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'N',
							'PMDSIRAP': 'N',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'N',
							'PMDSIRRJ': 'N',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'N',
							'PMDSIRDI': 'N',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'R',
							'PMDSIRRW': 'W',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'N',
							'PMDSSDH': 'N',
							'PNDSSDH': 'N',
							'PVDSSRE': 'N',
							'PMDSSRE': 'N',
							'PNDSSRE': 'N',
							'PVDSSEP': 'N',
							'PMDSSEP': 'N',
							'PNDSSEP': 'N',
							'PVDSSFS': 'N',
							'PMDSSFS': 'N',
							'PNDSSFS': 'N',
							'PVDSSPR': 'N',
							'PMDSSPR': 'N',
							'PNDSSPR': 'N',
							'PVDSSPD': 'N',
							'PMDSSPD': 'N',
							'PNDSSPD': 'N',
						}
					}
				}
			},
			'tags': {
				'_t': 'Array',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'headers': {
				'_t': 'Object',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'W',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'attributeCount': {
				'_t': 'Number',
				'_p': {
					'PMDSD': 'R',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'R',
					'PMDSBU': 'R',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'N'

				}
			},
			'draftVersion': {
				'_t': 'String',
				'_p': {
					'PMDSD': 'W',
					'PMDSE': 'R',
					'PMDSR': 'R',
					'PVDSD': 'R',
					'PVDSE': 'R',
					'PVDSR': 'R',
					'PVDSA': 'R',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'R',
					'PMDSBC': 'R',
					'PMDSBU': 'R',
					'PMDSBD': 'R',
					'PMDSPD': 'R',
					'PMDSPS': 'R',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'R',
					'PMDSIDPR': 'R',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'R',
					'PMDSIDPO': 'R',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'R',
					'PMDSIRSU': 'R',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'R',
					'PMDSIRAP': 'R',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'R',
					'PMDSIRRJ': 'R',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'R',
					'PMDSIRDI': 'R',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'R',
					'PMDSIRRW': 'R',
					'PNDSIRRW': 'R',
					'PVDSSDH': 'R',
					'PMDSSDH': 'R',
					'PNDSSDH': 'N',
					'PVDSSRE': 'R',
					'PMDSSRE': 'R',
					'PNDSSRE': 'N',
					'PVDSSEP': 'R',
					'PMDSSEP': 'R',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'R',
					'PNDSSFS': 'N',
					'PVDSSPR': 'R',
					'PMDSSPR': 'R',
					'PNDSSPR': 'N',
					'PVDSSPD': 'R',
					'PMDSSPD': 'R',
					'PNDSSPD': 'N',
				}
			},
			'_metadata': {
				'lastUpdated': {
					'_t': 'Date',
					'_p': {
						'PMDSD': 'R',
						'PMDSE': 'R',
						'PMDSR': 'R',
						'PVDSD': 'R',
						'PVDSE': 'R',
						'PVDSR': 'R',
						'PVDSA': 'R',
						////////////
						'PNDSB': 'N',
						'PVDSB': 'R',
						'PMDSBC': 'R',
						'PMDSBU': 'R',
						'PMDSBD': 'R',
						'PMDSPD': 'R',
						'PMDSPS': 'R',
						'PNDSPD': 'N',
						'PNDSPS': 'N',
						'PVDSIDPR': 'R',
						'PMDSIDPR': 'R',
						'PNDSIDPR': 'N',
						'PVDSIDPO': 'R',
						'PMDSIDPO': 'R',
						'PNDSIDPO': 'N',
						'PVDSIRSU': 'R',
						'PMDSIRSU': 'R',
						'PNDSIRSU': 'N',
						'PVDSIRAP': 'R',
						'PMDSIRAP': 'R',
						'PNDSIRAP': 'N',
						'PVDSIRRJ': 'R',
						'PMDSIRRJ': 'R',
						'PNDSIRRJ': 'N',
						'PVDSIRDI': 'R',
						'PMDSIRDI': 'R',
						'PNDSIRDI': 'N',
						'PVDSIRRW': 'R',
						'PMDSIRRW': 'R',
						'PNDSIRRW': 'N',
						'PVDSSDH': 'R',
						'PMDSSDH': 'R',
						'PNDSSDH': 'N',
						'PVDSSRE': 'R',
						'PMDSSRE': 'R',
						'PNDSSRE': 'N',
						'PVDSSEP': 'R',
						'PMDSSEP': 'R',
						'PNDSSEP': 'N',
						'PVDSSFS': 'R',
						'PMDSSFS': 'R',
						'PNDSSFS': 'N',
						'PVDSSPR': 'R',
						'PMDSSPR': 'R',
						'PNDSSPR': 'N',
						'PVDSSPD': 'R',
						'PMDSSPD': 'R',
						'PNDSSPD': 'N',
					}
				},
				'createdAt': {
					'_t': 'Date',
					'_p': {
						'PMDSD': 'R',
						'PMDSE': 'R',
						'PMDSR': 'R',
						'PVDSD': 'R',
						'PVDSE': 'R',
						'PVDSR': 'R',
						'PVDSA': 'R',
						////////////
						'PNDSB': 'N',
						'PVDSB': 'R',
						'PMDSBC': 'R',
						'PMDSBU': 'R',
						'PMDSBD': 'R',
						'PMDSPD': 'R',
						'PMDSPS': 'R',
						'PNDSPD': 'N',
						'PNDSPS': 'N',
						'PVDSIDPR': 'R',
						'PMDSIDPR': 'R',
						'PNDSIDPR': 'N',
						'PVDSIDPO': 'R',
						'PMDSIDPO': 'R',
						'PNDSIDPO': 'N',
						'PVDSIRSU': 'R',
						'PMDSIRSU': 'R',
						'PNDSIRSU': 'N',
						'PVDSIRAP': 'R',
						'PMDSIRAP': 'R',
						'PNDSIRAP': 'N',
						'PVDSIRRJ': 'R',
						'PMDSIRRJ': 'R',
						'PNDSIRRJ': 'N',
						'PVDSIRDI': 'R',
						'PMDSIRDI': 'R',
						'PNDSIRDI': 'N',
						'PVDSIRRW': 'R',
						'PMDSIRRW': 'R',
						'PNDSIRRW': 'N',
						'PVDSSDH': 'R',
						'PMDSSDH': 'R',
						'PNDSSDH': 'N',
						'PVDSSRE': 'R',
						'PMDSSRE': 'R',
						'PNDSSRE': 'N',
						'PVDSSEP': 'R',
						'PMDSSEP': 'R',
						'PNDSSEP': 'N',
						'PVDSSFS': 'R',
						'PMDSSFS': 'R',
						'PNDSSFS': 'N',
						'PVDSSPR': 'R',
						'PMDSSPR': 'R',
						'PNDSSPR': 'N',
						'PVDSSPD': 'R',
						'PMDSSPD': 'R',
						'PNDSSPD': 'N',
					}
				},
				'version': {
					'release': {
						'_t': 'Number',
						'_p': {
							'PMDSD': 'R',
							'PMDSE': 'R',
							'PMDSR': 'R',
							'PVDSD': 'R',
							'PVDSE': 'R',
							'PVDSR': 'R',
							'PVDSA': 'R',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'R',
							'PMDSBC': 'R',
							'PMDSBU': 'R',
							'PMDSBD': 'R',
							'PMDSPD': 'R',
							'PMDSPS': 'R',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'R',
							'PMDSIDPR': 'R',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'R',
							'PMDSIDPO': 'R',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'R',
							'PMDSIRSU': 'R',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'R',
							'PMDSIRAP': 'R',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'R',
							'PMDSIRRJ': 'R',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'R',
							'PMDSIRDI': 'R',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'R',
							'PMDSIRRW': 'R',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'R',
							'PMDSSDH': 'R',
							'PNDSSDH': 'N',
							'PVDSSRE': 'R',
							'PMDSSRE': 'R',
							'PNDSSRE': 'N',
							'PVDSSEP': 'R',
							'PMDSSEP': 'R',
							'PNDSSEP': 'N',
							'PVDSSFS': 'R',
							'PMDSSFS': 'R',
							'PNDSSFS': 'N',
							'PVDSSPR': 'R',
							'PMDSSPR': 'R',
							'PNDSSPR': 'N',
							'PVDSSPD': 'R',
							'PMDSSPD': 'R',
							'PNDSSPD': 'N',
						}
					},
					'document': {
						'_t': 'Number',
						'_p': {
							'PMDSD': 'R',
							'PMDSE': 'R',
							'PMDSR': 'R',
							'PVDSD': 'R',
							'PVDSE': 'R',
							'PVDSR': 'R',
							'PVDSA': 'R',
							////////////
							'PNDSB': 'N',
							'PVDSB': 'R',
							'PMDSBC': 'R',
							'PMDSBU': 'R',
							'PMDSBD': 'R',
							'PMDSPD': 'R',
							'PMDSPS': 'R',
							'PNDSPD': 'N',
							'PNDSPS': 'N',
							'PVDSIDPR': 'R',
							'PMDSIDPR': 'R',
							'PNDSIDPR': 'N',
							'PVDSIDPO': 'R',
							'PMDSIDPO': 'R',
							'PNDSIDPO': 'N',
							'PVDSIRSU': 'R',
							'PMDSIRSU': 'R',
							'PNDSIRSU': 'N',
							'PVDSIRAP': 'R',
							'PMDSIRAP': 'R',
							'PNDSIRAP': 'N',
							'PVDSIRRJ': 'R',
							'PMDSIRRJ': 'R',
							'PNDSIRRJ': 'N',
							'PVDSIRDI': 'R',
							'PMDSIRDI': 'R',
							'PNDSIRDI': 'N',
							'PVDSIRRW': 'R',
							'PMDSIRRW': 'R',
							'PNDSIRRW': 'N',
							'PVDSSDH': 'R',
							'PMDSSDH': 'R',
							'PNDSSDH': 'N',
							'PVDSSRE': 'R',
							'PMDSSRE': 'R',
							'PNDSSRE': 'N',
							'PVDSSEP': 'R',
							'PMDSSEP': 'R',
							'PNDSSEP': 'N',
							'PVDSSFS': 'R',
							'PMDSSFS': 'R',
							'PNDSSFS': 'N',
							'PVDSSPR': 'R',
							'PMDSSPR': 'R',
							'PNDSSPR': 'N',
							'PVDSSPD': 'R',
							'PMDSSPD': 'R',
							'PNDSSPD': 'N',
						}
					}
				}
			},
			'role': {
				'_t': 'Object',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'W',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'R',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'N',
					'PMDSSFS': 'N',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			},
			'enableSearchIndex': {
				'_t': 'Object',
				'_p': {
					'PMDSD': 'N',
					'PMDSE': 'N',
					'PMDSR': 'N',
					'PVDSD': 'N',
					'PVDSE': 'N',
					'PVDSR': 'N',
					'PVDSA': 'N',
					////////////
					'PNDSB': 'N',
					'PVDSB': 'N',
					'PMDSBC': 'N',
					'PMDSBU': 'N',
					'PMDSBD': 'N',
					'PMDSPD': 'N',
					'PMDSPS': 'N',
					'PNDSPD': 'N',
					'PNDSPS': 'N',
					'PVDSIDPR': 'N',
					'PMDSIDPR': 'N',
					'PNDSIDPR': 'N',
					'PVDSIDPO': 'N',
					'PMDSIDPO': 'N',
					'PNDSIDPO': 'N',
					'PVDSIRSU': 'N',
					'PMDSIRSU': 'N',
					'PNDSIRSU': 'N',
					'PVDSIRAP': 'N',
					'PMDSIRAP': 'N',
					'PNDSIRAP': 'N',
					'PVDSIRRJ': 'N',
					'PMDSIRRJ': 'N',
					'PNDSIRRJ': 'N',
					'PVDSIRDI': 'N',
					'PMDSIRDI': 'N',
					'PNDSIRDI': 'N',
					'PVDSIRRW': 'N',
					'PMDSIRRW': 'N',
					'PNDSIRRW': 'N',
					'PVDSSDH': 'N',
					'PMDSSDH': 'N',
					'PNDSSDH': 'N',
					'PVDSSRE': 'N',
					'PMDSSRE': 'N',
					'PNDSSRE': 'N',
					'PVDSSEP': 'N',
					'PMDSSEP': 'N',
					'PNDSSEP': 'N',
					'PVDSSFS': 'R',
					'PMDSSFS': 'W',
					'PNDSSFS': 'N',
					'PVDSSPR': 'N',
					'PMDSSPR': 'N',
					'PNDSSPR': 'N',
					'PVDSSPD': 'N',
					'PMDSSPD': 'N',
					'PNDSSPD': 'N',
				}
			}
		}
	},
	{
		'entity': 'GS',
		'app': 'Adam',
		'entityName': 'Library',
		'roles': [
			{ id: 'PML', name: 'Manage Library', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }] },
			{ id: 'PVL', name: 'View Library', operations: [{ method: 'GET' }] },
			{ id: 'PNL', name: 'No Access Library', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] }
		],
		'default': 'R',
		'type': 'author',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			},
			'name': {
				'_t': 'String',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			},
			'app': {
				'_t': 'String',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			},
			'definition': {
				'_t': 'String',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			}
			,
			'services': {
				'_t': 'Array',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			},
			'_metadata': {
				'lastUpdated': {
					'_t': 'Date',
					'_p': {
						'PNL': 'N',
						'PML': 'W',
						'PVL': 'R'
					}
				},
				'createdAt': {
					'_t': 'Date',
					'_p': {
						'PNL': 'N',
						'PML': 'W',
						'PVL': 'R'
					}
				},
				'version': {
					'release': {
						'_t': 'Number',
						'_p': {
							'PNL': 'N',
							'PML': 'W',
							'PVL': 'R'
						}
					},
					'document': {
						'_t': 'Number',
						'_p': {
							'PNL': 'N',
							'PML': 'W',
							'PVL': 'R'
						}
					}
				}
			},
			'attributeList': {
				'_t': 'Array',
				'_p': {
					'PNL': 'N',
					'PML': 'W',
					'PVL': 'R'
				}
			}
		}
	},
	{
		'entity': 'USER',
		'app': 'Adam',
		'entityName': 'User',
		'type': 'author',
		'roles': [
			{ id: 'PMU', name: 'Manage Users', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'GET' }] },
			{ id: 'PVU', name: 'View Users', operations: [{ method: 'GET' }] },
		],
		'default': 'R',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PMU': 'R',
					'PVU': 'R'
				}
			},
			'username': {
				'_t': 'String',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'password': {
				'_t': 'String',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'isActive': {
				'_t': 'Boolean',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'roles': {
				'_t': 'Array',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'basicDetails': {
				'_t': 'Object',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'sessionTime': {
				'_t': 'Number',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'enableSessionRefresh': {
				'_t': 'Boolean',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'isSuperAdmin': {
				'_t': 'Boolean',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'accessControl': {
				'_t': 'Object',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'auth': {
				'_t': 'Object',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'bot': {
				'_t': 'Boolean',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'attributes': {
				'_t': 'Object',
				'_p': {
					'PMU': 'W',
					'PVU': 'R'
				}
			},
			'_metadata': {
				'lastUpdated': {
					'_t': 'Date',
					'_p': {
						'PMU': 'R',
						'PVU': 'R'
					}
				},
				'createdAt': {
					'_t': 'Date',
					'_p': {
						'PMU': 'R',
						'PVU': 'R'
					}
				},
				'version': {
					'release': {
						'_t': 'Number',
						'_p': {
							'PMU': 'R',
							'PVU': 'R'
						}
					},
					'document': {
						'_t': 'Number',
						'_p': {
							'PMU': 'R',
							'PVU': 'R'
						}
					}
				}
			}
		}
	},
	{
		'entity': 'GROUP',
		'app': 'Adam',
		'entityName': 'Group',
		'type': 'author',
		'roles': [
			{ id: 'PMG', name: 'Manage Groups', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PVG', name: 'View Groups', operations: [{ method: 'GET' }] },
		],
		'default': 'R',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PMG': 'R',
					'PVG': 'R'
				}
			},
			'name': {
				'_t': 'String',
				'_p': {
					'PMG': 'W',
					'PVG': 'R'
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PMG': 'W',
					'PVG': 'R'
				}
			},
			'isActive': {
				'_t': 'Boolean',
				'_p': {
					'PMG': 'W',
					'PVG': 'R'
				}
			},
			'roles': {
				'_t': 'Array',
				'_p': {
					'PMG': 'W',
					'PVG': 'R'
				}
			},
			'users': {
				'_t': 'Array',
				'_p': {
					'PMG': 'W',
					'PVG': 'R'
				}
			},
			'_metadata': {
				'lastUpdated': {
					'_t': 'Date',
					'_p': {
						'PMG': 'R',
						'PVG': 'R'
					}
				},
				'createdAt': {
					'_t': 'Date',
					'_p': {
						'PMG': 'R',
						'PVG': 'R'
					}
				},
				'version': {
					'release': {
						'_t': 'Number',
						'_p': {
							'PMG': 'R',
							'PVG': 'R'
						}
					},
					'document': {
						'_t': 'Number',
						'_p': {
							'PMG': 'R',
							'PVG': 'R'
						}
					}
				}
			}
		}
	},
	{
		'entity': 'PM',
		'app': 'Adam',
		'entityName': 'Partner Manager',
		'type': 'author',
		'roles': [
			{ id: 'PMPH', name: 'Manage Partner Headers', operations: [{ method: 'PUT' }] },
			{ id: 'PVPH', name: 'View Partner Header', operations: [{ method: 'GET' }] },
			////////////

			{ id: 'PVPB', name: 'View Partner', operations: [{ method: 'GET' }] },
			{ id: 'PNPB', name: 'No Access Partner', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PMPBC', name: 'Create Partner', operations: [{ method: 'POST' }] },
			{ id: 'PMPBU', name: 'Update Partner', operations: [{ method: 'PUT' }] },
			{ id: 'PMPBD', name: 'Delete Partner', operations: [{ method: 'DELETE' }] },
			{ id: 'PNPFMB', name: 'No Access Partner flow', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PVPFMB', name: 'View Partner Flow', operations: [{ method: 'GET' }] },
			{ id: 'PMPFMBC', name: 'Create Partner Flow', operations: [{method: 'POST' }] },
			{ id: 'PMPFMBU', name: 'Update Partner Flow', operations: [{ method: 'PUT' }] },
			{ id: 'PMPFMBD', name: 'Delete Partner Flow', operations: [{ method: 'DELETE' },] },
			{ id: 'PNPFPD', name: 'No Access Partner flow Deploy', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PNPFPS', name: 'No Access Partner flow start/stop', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PMPFPD', name: 'Manage Partner flow Deploy', operations: [{ method: 'PUT' }] },
			{ id: 'PMPFPS', name: 'Manage Partner flow Start/Stop', operations: [{ method: 'PUT' }] },
			{ id: 'PNPP', name: 'No Access Partner Profile', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PMPPC', name: 'Manage Partner Profile Create', operations: [{ method: 'POST' }, { method: 'PUT' }] },
			{ id: 'PMPPD', name: 'Manage Partner Profile Delete', operations: [{ method: 'DELETE' }, { method: 'PUT' }] },
			{ id: 'PNPH', name: 'No Access Partner Headers', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PNPM', name: 'No Access Partner Management Tab', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PMPM', name: 'Manage Access Partner Management Tab', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
		],
		'default': 'R',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					'PVPP': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'R',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'app': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'name': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'logo': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'N',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'N',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'N'
				}
			},
			'status': {
				'_t': 'String',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'N',
					'PNPB': 'N',
					'PMPBC': 'N',
					'PMPBU': 'N',
					'PMPBD': 'N',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'W',
					'PMPFMBD': 'W',
					'PMPFMBU': 'W',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'W',
					'PMPFPS': 'W',
					'PNPP': 'N',
					'PVPP': 'N',
					'PMPPC': 'N',
					'PMPPD': 'N',
					'PNPH': 'N'
				}
			},
			'comment': {
				'_t': 'String',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'R',
					'PNPFMB': 'N',
					'PVPFMB': 'N',
					'PMPFMBC': 'N',
					'PMPFMBD': 'N',
					'PMPFMBU': 'N',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'N',
					'PMPFPS': 'N',
					'PNPP': 'N',
					'PVPP': 'N',
					'PMPPC': 'N',
					'PMPPD': 'N',
					'PNPH': 'N'
				}
			},
			'secrets': {
				'_t': 'Array',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'N',
					'PNPB': 'N',
					'PMPBC': 'N',
					'PMPBU': 'N',
					'PMPBD': 'N',
					'PNPFMB': 'N',
					'PVPFMB': 'N',
					'PMPFMBC': 'N',
					'PMPFMBD': 'N',
					'PMPFMBU': 'N',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'N',
					'PMPFPS': 'N',
					'PNPP': 'N',
					'PVPP': 'R',
					'PMPPC': 'W',
					'PMPPD': 'W',
					'PNPH': 'N'
				}
			},
			'flows': {
				'_t': 'Array',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'N',
					'PNPB': 'N',
					'PMPBC': 'N',
					'PMPBU': 'N',
					'PMPBD': 'N',
					'PNPFMB': 'N',
					'PVPFMB': 'R',
					'PMPFMBC': 'W',
					'PMPFMBD': 'W',
					'PMPFMBU': 'W',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'N',
					'PVPP': 'N',
					'PMPPC': 'N',
					'PMPPD': 'N',
					'PNPH': 'N'
				}
			},
			'notifications': {
				'_t': 'Array',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'R',
					'PNPB': 'R',
					'PMPBC': 'R',
					'PMPBU': 'R',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'agentID': {
				'_t': 'String',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'N',
					'PNPB': 'N',
					'PMPBC': 'N',
					'PMPBU': 'N',
					'PMPBD': 'N',
					'PNPFMB': 'N',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'N',
					'PVPP': 'N',
					'PMPPC': 'N',
					'PMPPD': 'N',
					'PNPH': 'N'
				}
			},
			'serverReadTimeout': {
				'_t': 'String',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'R',
					'PMPBU': 'R',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'serverWriteTimeout': {
				'_t': 'String',
				'_p': {
					'PMPH': 'N',
					'PVPH': 'N',
					////
					'PVPB': 'R',
					'PNPB': 'R',
					'PMPBC': 'R',
					'PMPBU': 'R',
					'PMPBD': 'R',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'R',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'R'
				}
			},
			'headers': {
				'_t': 'String',
				'_p': {
					'PMPH': 'W',
					'PVPH': 'R',
					////
					'PVPB': 'N',
					'PNPB': 'N',
					'PMPBC': 'N',
					'PMPBU': 'N',
					'PMPBD': 'N',
					'PNPFMB': 'N',
					'PVPFMB': 'N',
					'PMPFMBC': 'N',
					'PMPFMBD': 'N',
					'PMPFMBU': 'N',
					'PNPFPD': 'N',
					'PNPFPS': 'N',
					'PMPFPD': 'N',
					'PMPFPS': 'N',
					'PNPP': 'N',
					'PVPP': 'N',
					'PMPPC': 'N',
					'PMPPD': 'N',
					'PNPH': 'N'
				}
			},
			'_metadata': {
				'_t': 'String',
				'_p': {
					'PMPH': 'R',
					'PVPH': 'R',
					////
					'PVPB': 'R',
					'PNPB': 'N',
					'PMPBC': 'W',
					'PMPBU': 'W',
					'PMPBD': 'W',
					'PNPFMB': 'R',
					'PVPFMB': 'R',
					'PMPFMBC': 'R',
					'PMPFMBD': 'R',
					'PMPFMBU': 'R',
					'PNPFPD': 'R',
					'PNPFPS': 'R',
					'PMPFPD': 'R',
					'PMPFPS': 'R',
					'PNPP': 'N',
					'PVPP': 'R',
					'PMPPC': 'R',
					'PMPPD': 'R',
					'PNPH': 'N'
				}
			}
		}
	},
	{
		'entity': 'NS',
		'app': 'Adam',
		'entityName': 'Nano Service',
		'type': 'author',
		'roles': [
			{ id: 'PVNSB', name: 'View Nano Service Basic Details', operations: [{ method: 'GET' }] },
			{ id: 'PNNSB', name: 'No Access Nano Service', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PMNSBC', name: 'Create Nano Servcie', operations: [{ method: 'POST' }] },
			{ id: 'PMNSBU', name: 'Update Nano Service', operations: [{ method: 'PUT' }] },
			{ id: 'PMNSBD', name: 'Delete Nano Service', operations: [{ method: 'DELETE' }] },
			{ id: 'PMNSIO', name: 'Manage input/output', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PVNSIO', name: 'View input/output', operations: [{ method: 'GET' }] },
			{ id: 'PNNSIO', name: 'No Access input/output', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PVNSURL', name: 'View URL', operations: [{ method: 'GET' }] },
			{ id: 'PMNSURL', name: 'Manage URL', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNNSURL', name: 'No Access URL', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
			{ id: 'PVNSH', name: 'View Headers', operations: [ { method: 'GET' }] },
			{ id: 'PMNSH', name: 'Manage Headers', operations: [{ method: 'PUT' }, { method: 'POST' }] },
			{ id: 'PNNSH', name: 'No Access Headers', operations: [{ method: 'PUT' }, { method: 'POST' }, { method: 'DELETE' }, { method: 'GET' }] },
		],
		'default': 'R',
		'fields': {
			'_id': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'R',
					'PNNSB': 'N',
					'PMNSBC': 'W',
					'PMNSBU': 'W',
					'PMNSBD': 'R',
					'PNNSIO': 'N',
					'PMNSIO': 'R',
					'PVNSIO': 'R',
					'PVNSURL': 'R',
					'PMNSURL': 'R',
					'PNNSURL': 'N',
					'PVNSH': 'R',
					'PMNSH': 'R',
					'PNNSH': 'R'
				}
			},
			'app': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'R',
					'PNNSB': 'N',
					'PMNSBC': 'W',
					'PMNSBU': 'W',
					'PMNSBD': 'R',
					'PNNSIO': 'N',
					'PMNSIO': 'R',
					'PVNSIO': 'R',
					'PVNSURL': 'R',
					'PMNSURL': 'R',
					'PNNSURL': 'N',
					'PVNSH': 'R',
					'PMNSH': 'R',
					'PNNSH': 'N'
				}
			},
			'name': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'R',
					'PNNSB': 'N',
					'PMNSBC': 'W',
					'PMNSBU': 'W',
					'PMNSBD': 'R',
					'PNNSIO': 'N',
					'PMNSIO': 'R',
					'PVNSIO': 'R',
					'PVNSURL': 'R',
					'PMNSURL': 'R',
					'PNNSURL': 'N',
					'PVNSH': 'R',
					'PMNSH': 'R',
					'PNNSH': 'N'
				}
			},
			'description': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'R',
					'PNNSB': 'N',
					'PMNSBC': 'W',
					'PMNSBU': 'W',
					'PMNSBD': 'R',
					'PNNSIO': 'N',
					'PMNSIO': 'R',
					'PVNSIO': 'R',
					'PVNSURL': 'R',
					'PMNSURL': 'R',
					'PNNSURL': 'N',
					'PVNSH': 'R',
					'PMNSH': 'R',
					'PNNSH': 'N'
				}
			},
			'in': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'N',
					'PNNSB': 'N',
					'PMNSBC': 'N',
					'PMNSBU': 'N',
					'PMNSBD': 'N',
					'PNNSIO': 'N',
					'PMNSIO': 'W',
					'PVNSIO': 'R',
					'PVNSURL': 'N',
					'PMNSURL': 'N',
					'PNNSURL': 'N',
					'PVNSH': 'N',
					'PMNSH': 'N',
					'PNNSH': 'N'
				}
			},
			'out': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'N',
					'PNNSB': 'N',
					'PMNSBC': 'N',
					'PMNSBU': 'N',
					'PMNSBD': 'N',
					'PNNSIO': 'N',
					'PMNSIO': 'W',
					'PVNSIO': 'R',
					'PVNSURL': 'N',
					'PMNSURL': 'N',
					'PNNSURL': 'N',
					'PVNSH': 'N',
					'PMNSH': 'N',
					'PNNSH': 'N'
				}
			},
			'url': {
				'_t': 'String',
				'_p': {
					'PVNSB': 'N',
					'PNNSB': 'N',
					'PMNSBC': 'N',
					'PMNSBU': 'N',
					'PMNSBD': 'N',
					'PNNSIO': 'N',
					'PMNSIO': 'N',
					'PVNSIO': 'N',
					'PVNSURL': 'R',
					'PMNSURL': 'W',
					'PNNSURL': 'N',
					'PVNSH': 'N',
					'PMNSH': 'N',
					'PNNSH': 'N'
				}
			},
			'allowTrustedConnections': {
				'_t': 'Array',
				'_p': {
					'PVNSB': 'N',
					'PNNSB': 'N',
					'PMNSBC': 'N',
					'PMNSBU': 'N',
					'PMNSBD': 'N',
					'PNNSIO': 'N',
					'PMNSIO': 'N',
					'PVNSIO': 'N',
					'PVNSURL': 'R',
					'PMNSURL': 'W',
					'PNNSURL': 'N',
					'PVNSH': 'N',
					'PMNSH': 'N',
					'PNNSH': 'N'
				}
			},
			'headers': {
				'_t': 'Array',
				'_p': {
					'PVNSB': 'N',
					'PNNSB': 'N',
					'PMNSBC': 'N',
					'PMNSBU': 'N',
					'PMNSBD': 'N',
					'PNNSIO': 'N',
					'PMNSIO': 'N',
					'PVNSIO': 'N',
					'PVNSURL': 'N',
					'PMNSURL': 'N',
					'PNNSURL': 'N',
					'PVNSH': 'R',
					'PMNSH': 'W',
					'PNNSH': 'N'
				}
			},
			'_metadata': {
				'_t': 'Array',
				'_p': {
					'PVNSB': 'R',
					'PNNSB': 'N',
					'PMNSBC': 'W',
					'PMNSBU': 'W',
					'PMNSBD': 'R',
					'PNNSIO': 'R',
					'PMNSIO': 'R',
					'PVNSIO': 'R',
					'PVNSURL': 'R',
					'PMNSURL': 'R',
					'PNNSURL': 'R',
					'PVNSH': 'R',
					'PMNSH': 'R',
					'PNNSH': 'R'
				}
			}
		}
	}
];